FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install
COPY . .
EXPOSE 3000 3001
CMD ["pnpm", "run", "start:dev"]
